name: Word API

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ./cache
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.run_id }}
          restore-keys: |-
            ${{ runner.os }}-${{ github.workflow }}-
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Process Word API
        run: python word.py
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
